#actual size of the window
SCREEN_WIDTH = 80
SCREEN_HEIGHT = 50
 
#size of the map portion shown on-screen
CAMERA_WIDTH = 80
CAMERA_HEIGHT = 40

#size of the map
MAP_WIDTH = 80
MAP_HEIGHT = 80
 
#sizes and coordinates relevant for the GUI
BAR_WIDTH = 30
PANEL_HEIGHT = 10
PANEL_Y = SCREEN_HEIGHT - PANEL_HEIGHT
MSG_X = BAR_WIDTH + 2
MSG_WIDTH = SCREEN_WIDTH - BAR_WIDTH - 2
MSG_HEIGHT = PANEL_HEIGHT - 1
INVENTORY_WIDTH = 50
CHARACTER_SCREEN_WIDTH = 30
LEVEL_SCREEN_WIDTH = 40
MSG_LIMIT = 150
 
#parameters for dungeon generator
ROOM_MAX_SIZE = 20
ROOM_MIN_SIZE = 4
MAX_ROOMS = 60

#constants for bsp
DEPTH = 5
MIN_SIZE = 10
FULL_ROOMS = False

#for hp regeneration
HP_REGEN_TIME = 100
 
#spell values
HEAL_AMOUNT = 40
GREATHEAL_AMOUNT = 80
LIGHTNING_DAMAGE = 30
LIGHTNING_RANGE = 5
CONFUSE_RANGE = 8
CONFUSE_NUM_TURNS = 10
PARALYZE_RANGE = 8
PARALYZE_NUM_TURNS = 10
FIREBALL_RADIUS = 3
FIREBALL_DAMAGE = 25
MAGICMISSILE_DAMAGE = 40
MAGICMISSILE_RANGE = 10
 
#experience and level-ups
LEVEL_UP_BASE = 200
LEVEL_UP_FACTOR = 150
 
 
FOV_ALGO = 0  #default FOV algorithm
FOV_LIGHT_WALLS = True  #light walls or not
TORCH_RADIUS = 15
 
LIMIT_FPS = 20  #20 frames-per-second maximum